=== dingdinggithub/kevin-generator/src/main/resources/dtd/genCode.dtd
<!ELEMENT project (table+)>
	<!ELEMENT table (#PCDATA)>
	<!ATTLIST project name CDATA #REQUIRED basepackage CDATA #REQUIRED path CDATA #REQUIRED>
	<!ATTLIST table src CDATA #REQUIRED>

=== dingdinggithub/kevin-generator/src/main/resources/genCode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "dtd/genCode.dtd">
<!-- 
name：项目名称
basepackage:基础包名
path：项目路径
 -->
<project name="回忆录" basepackage="com.kevin.mem.mng" path="D:\project\kevin">
	<table src="tables/mem/user.xml"/>
	<table src="tables/mem/role.xml"/>
	<table src="tables/mem/module.xml"/>
	<table src="tables/mem/authModule.xml"/>
	<table src="tables/mem/roleUser.xml"/>
	<table src="tables/mem/roleAuth.xml"/>
	<table src="tables/mem/dept.xml"/>
</project>
