=== dingdinggithub/kevin-generator/src/main/resources/dtd/table.dtd
<!ELEMENT entity (id,property+)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT property (#PCDATA)>
	<!ATTLIST entity name CDATA #REQUIRED table CDATA #REQUIRED description CDATA #REQUIRED author CDATA #REQUIRED since CDATA #REQUIRED>
	<!ATTLIST id name CDATA #REQUIRED type ( int | long | string | date ) "string" description  CDATA #REQUIRED column CDATA #REQUIRED>
	<!ATTLIST property name CDATA #REQUIRED type ( int | long | string | date | decimal) "string" description  CDATA #REQUIRED column CDATA #REQUIRED maxlength CDATA #IMPLIED dateFmt CDATA #IMPLIED>

=== dingdinggithub/kevin-generator/target/classes/tables/worker/jsgzlhz.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="jsgzlhz" table="jsgzlhz" description="教师工作量汇总表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="ID" column="ID" type="string" description="主键"/>
<property	name="JSGH"  		 column="JSGH" type="string"  maxlength="20"   description="教师工号"   />
<property	name="JSXM"  		 column="JSXM" type="string"  maxlength="20"     description="教师姓名"   />
<property	name="ZGXW"      		 column="ZGXW" type="string"  maxlength="30"   description="最高学位"     />
<property	name="ZC"     		 column="ZC" type="string"  maxlength="10"   description="教室职称"     />
<property	name="ZJXGZL"      		 column="ZJXGZL"  type="decimal" maxlength="10"   description="总教学工作量"      />
<property	name="ZZDGZL"  		 column="ZZDGZL" type="decimal" maxlength="10"   description="总指导工作量"     />
<property	name="ZJ"  		 column="ZJ" type="decimal" maxlength="10"   description="总计"     />
<property	name="GZLHZXNXQ"  		 column="GZLHZ_XNXQ" type="string"  maxlength="50"   description="工作量学年学期"   />
</entity>

=== dingdinggithub/kevin-generator/target/classes/tables/else/daily_attendance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="DailyAttendance" table="daily_attendance" description="日常考勤" author="刘伟伟" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="int" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date 选择其中一个
		description:描述,生成注释需要，页面内容
	 -->
	<property name="department" column="department" type="string" description="所属部门"/>
	<property name="userId" column="user_id" type="string" description="用户id"/>
	<property name="time" column="time" type="date" description="时间"/>
	<property name="state" column="state" type="int" description="状态"/>
	<property name="longitude" column="longitude" type="string" description="经度"/>
	<property name="latitude" column="latitude" type="string" description="纬度"/>
	<property name="distance" column="distance" type="int" description="距离"/>
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/else/bfdw.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--                                                                            
name:类名称,首字母大写                                                          
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)                             
description：（类的中文名称）页面中用到                                         
author：类的开发作者（注释会用到）                                              
version:类的开发版本                                                            
 -->                                                                            
<entity name="bfdw" table="bfdw" description="帮扶单位表" author="孙强强" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>                  
	<!--                                                                          
		name:表示属性名称                                                           
		type：属性类型,int | long | string | date |decimal选择其中一个              
		description:描述,生成注释需要，页面内容                                     
	 -->
<property	name="BFBH"  		 column="BFBH" type="string"  maxlength="255"      description="帮扶编号" />
<property	name="JTBH"  		 column="JTBH" type="string"  maxlength="18"     description="家庭编号"   />
<property	name="BFDW"  		 column="BFDW" type="string"  maxlength="50"     description="帮扶单位"   />
<property	name="XM"      		 column="XM" type="string"  maxlength="30"   description="姓名"     />
<property	name="ZW"     		 column="ZW" type="string"  maxlength="20"   description="职务"     />
<property	name="XB"      		 column="XB" type="string"  maxlength="2"   description="性别"      />
<property	name="SFZH"  		 column="SFZH" type="string"  maxlength="18"   description="身份证号"     />
<property	name="ZZMM"  		 column="ZZMM" type="string"  maxlength="20"   description="政治面貌"     />
<property	name="BFKSSJ"  column="BFKSSJ" type="date"     description="帮扶开始时间" dateFmt="yyyy-MM-dd"    />
<property	name="BFTPSJ"  column="BFTPSJ" type="date"    description="帮扶脱贫时间"  dateFmt="yyyy-MM-dd"   />
<property	name="ZYBFCS"  column="ZYBFCS" type="string"  maxlength="255"   description="主要帮扶措施"    />
<property	name="LXDH"   	 column="LXDH" type="string"  maxlength="20"   description="联系电话"     />
<property name="inputTime" column="input_time" type="date" maxlength="0" description="录入时间" dateFmt="yyyy-MM-dd HH:mm:ss"/> 
<property name="inputUser" column="input_user" type="string" maxlength="255" description="录入人"  />

</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/fupin/PKCTPFA.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="pkctpfa" table="pkctpfa" description="县区脱贫路径规划" author="niuxin" since="1.0">
<id name="QHDM" column="QHDM" type="string" description="区划代码"/>   
	<property name="TBND" column="TBND" type="string" maxlength="4" description="填报年度"/> 
	<property name="QHMC" column="QHMC" type="string" maxlength="40" description="贫困村名称" />
	<property name="CZMJ" column="CZMJ" type="decimal" maxlength="12" description="村总面积" /> 
	<property name="ZRCGS" column="ZRCGS" type="int"  description="自然村个数" /> 
	<property name="ZHS" column="ZHS" type="int"  description="总户数" /> 
	<property name="ZRKS" column="ZRKS" type="int"  description="总人数" /> 
	<property name="WBHJZGYHS" column="WBH_JZGYHS" type="int"  description="五保户_集中供养户数" /> 
	<property name="WBHJZGYRKS" column="WBH_JZGYRKS" type="int"  description="五保户_集中供养人口数" /> 
	<property name="WBHFSGYHS" column="WBH_FSGYHS" type="int"  description="五保户_分散供养户数" /> 
	<property name="WBHFSGYRKS" column="WBH_FSGYRKS" type="int"  description="五保户_分散供养人口数" /> 
	<property name="DBHJZGYHS" column="DBH_JZGYHS" type="int"  description="低保户_集中供养户数" /> 
	<property name="DBHJZGYRKS" column="DBH_JZGYRKS" type="int"  description="低保户_集中供人口数" /> 
	<property name="CJTJJSR" column="CJTJJSR" type="decimal" maxlength="12" description="村集体经济收入" /> 
	<property name="PKHZHS" column="PKH_ZHS" type="int"  description="贫困户_总户数" /> 
	<property name="PKHZRKS" column="PKH_ZRKS" type="int"  description="贫困户_总人数" /> 
	<property name="WBPKHHS" column="WBPKH_HS" type="int"  description="五保贫困户_户数" /> 
	<property name="WBPKHRKS" column="WBPKH_RKS" type="int"  description="五保贫困户_人数" /> 
	<property name="DBPKHHS" column="DBPKH_HS" type="int"  description="低保贫困户_户数" /> 
	<property name="DBPKHRKS" column="DBPKH_RKS" type="int"  description="低保贫困户_人数" /> 
	<property name="YBPKHHS" column="YBPKH_HS" type="int"  description="一般贫困户_户数" /> 
	<property name="YBPKHRKS" column="YBPKH_RKS" type="int"  description="一般贫困户_人数" /> 
	<property name="PKFSL" column="PKFSL" type="decimal" maxlength="6" description="贫困发生率" /> 
	<property name="CZDCYLX" column="CZDCYLX" type="string" maxlength="20" description="村主导产业类型" />
	<property name="CZDCYGM" column="CZDCYGM" type="decimal" maxlength="12" description="村主导产业规模" /> 
	<property name="CZDCYSYHS" column="CZDCY_SYHS" type="int"  description="村主导产业_受益户数" /> 
	<property name="CZDCYSYRKS" column="CZDCY_SYRKS" type="int"  description="村主导产业_受益人口数" /> 
	<property name="CZDCYSYPKHS" column="CZDCY_SYPKHS" type="int"  description="村主导产业_受益贫困户数" /> 
	<property name="CZDCYSYPKRKS" column="CZDCY_SYPKRKS" type="int"  description="村主导产业_受益贫困人口数" /> 
	<property name="YBZPHS" column="YBZP_HS" type="int"  description="因病致贫_户数" /> 
	<property name="YBZPRKS" column="YBZP_RKS" type="int"  description="因病致贫_人口数" /> 
	<property name="YCZPHS" column="YCZP_HS" type="int"  description="因残致贫_户数" /> 
	<property name="YCZPRKS" column="YCZP_RKS" type="int"  description="因残致贫_人口数" /> 
	<property name="YXZPHS" column="YXZP_HS" type="int"  description="因学致贫_户数" /> 
	<property name="YXZPRKS" column="YXZP_RKS" type="int"  description="因学致贫_人口数" /> 
	<property name="YZZPHS" column="YZZP_HS" type="int"  description="因灾致贫_户数" /> 
	<property name="YZZPRKS" column="YZZP_RKS" type="int"  description="因灾致贫_人口数" /> 
	<property name="QTDZPHS" column="QTDZP_HS" type="int"  description="缺土地致贫_户数" /> 
	<property name="QTDZPRKS" column="QTDZP_RKS" type="int"  description="缺土地致贫_人口数" /> 
	<property name="QSZPHS" column="QSZP_HS" type="int"  description="缺水致贫_户数" /> 
	<property name="QSZPRKS" column="QSZP_RKS" type="int"  description="缺水致贫_人口数" /> 
	<property name="QJSZPHS" column="QJSZP_HS" type="int"  description="缺技术致贫_户数" /> 
	<property name="QJSZPRKS" column="QJSZP_RKS" type="int"  description="缺技术致贫_人口数" /> 
	<property name="QLDLZPHS" column="QLDLZP_HS" type="int"  description="缺劳动力致贫_户数" /> 
	<property name="QLDLZPRKS" column="QLDLZP_RKS" type="int"  description="缺劳动力致贫_人口数" /> 
	<property name="QZJZPHS" column="QZJZP_HS" type="int"  description="缺资金致贫_户数" /> 
	<property name="QZJZPRKS" column="QZJZP_RKS" type="int"  description="缺资金致贫_人口数" /> 
	<property name="JTTJLHHS" column="JTTJLH_HS" type="int"  description="交通条件落后_户数" /> 
	<property name="JTTJLHRKS" column="JTTJLH_RKS" type="int"  description="交通条件落后_人口数" /> 
	<property name="ZSDLBZHS" column="ZSDLBZ_HS" type="int"  description="自身动力发展不足户数" /> 
	<property name="ZSDLBZRKS" column="ZSDLBZ_RKS" type="int"  description="自身动力发展不足人口数" /> 
	<property name="SFTGL" column="SFTGL" type="string" maxlength="1" description="是否通公路"/> 
	<property name="SFTKYBC" column="SFTKYBC" type="string" maxlength="1" description="是否通客运班车" />
	<property name="SFYSAQ" column="SFYSAQ" type="string" maxlength="1" description="填报是否饮水安全"/> 
	<property name="SFYWHZX" column="SFYWHZX" type="string" maxlength="1" description="是否有文化中心" />
	<property name="SFMZYDXQ" column="SFMZYDXQ" type="string" maxlength="1" description="是否满足用电"/> 
	<property name="SFTGBDS" column="SFTGBDS" type="string" maxlength="1" description="是否通广播电视" />
	<property name="SFYXCYS" column="SFYXCYS" type="string" maxlength="1" description="是否有乡村医生"/> 
	<property name="SFTKD" column="SFTKD" type="string" maxlength="1" description="是否通宽带" />
</entity>

=== dingdinggithub/kevin-generator/target/classes/tables/else/Member.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="Member" table="krzj_users" description="会员" author="余进" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="string" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date 选择其中一个
		description:描述,生成注释需要，页面内容
	 -->
	<property name="name" column="name" type="string" description="会员姓名"/>
	<property name="username" column="username" type="string" description="用户名"/>
	<property name="password" column="password" type="string" description="会员密码"/>
	<property name="phone" column="phone" type="string" description="会员手机"/>
	<property name="email" column="email" type="string" description="会员Email"/>
	<property name="createTime" column="create_time" type="string" description="注册时间"/>
	<property name="status" column="status" type="int" description="会员状态"/>
</entity>

=== dingdinggithub/kevin-generator/target/classes/tables/worker/kcxx.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="kcxx" table="kcxx" description="课程信息表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="ID" column="ID" type="string" description="主键"/>
<property	name="KCDM"  		 column="KCDM" type="string"  maxlength="25" description="课程代码"   />
<property	name="KCMC"  		 column="KCMC" type="string"  maxlength="25"     description="课程名称"   />
<property	name="KCXZ"      		 column="KCXZ" type="string"  maxlength="10"   description="课程性质"     />
<property	name="KCKSQK"     		 column="KCKSQK" type="string"  maxlength="10"   description="课程开设情况"     />
<property	name="SXBJ"      		 column="SXBJ" type="string"  maxlength="50"   description="所学班级"      />
<property	name="XXNJ"  		 column="XXNJ" type="string"   maxlength="10" description="学习年级"     />
<property	name="RKJS"  		 column="RKJS" type="string"  maxlength="10"   description="任课教师"     />
<property	name="KCSKZS"  		 column="KCSKZS" type="string"  maxlength="50"  description="课程授课周数"    />
<property	name="MZKS"  		 column="MZKS" type="string"  maxlength="10"     description="每周课时"   />
<property	name="MZKSFP"      		 column="MZKSFP" type="string"  maxlength="50"   description="每周课时分配"      />
<property	name="ZYSYS"  		 column="ZYSYS" type="string"   maxlength="50" description="专业实验室"     />
<property	name="ZKS"  		 column="ZKS" type="string"  maxlength="10"   description="总课时"     />
<property	name="SFHB"  		 column="SFHB" type="string"  maxlength="2"  description="是否合班"    />
<property	name="KCXNXQ"  		 column="KCXNXQ" type="string"  maxlength="50"     description="课程学年学期"   />
<property	name="SFFZ"      		 column="SFFZ" type="string"  maxlength="2"   description="是否分组"      />
<property	name="SFLK"  		 column="SFLK" type="string"   maxlength="2" description="是否联课"     />
<property	name="WPJSSUDW"  		 column="WPJS_SUDW" type="string"  maxlength="50"   description="外聘教师所属单位"     />
<property	name="WPJSLXFS"  		 column="WPJS_LXFS" type="string"  maxlength="50"  description="外聘教师联系方式"    />
<property	name="PKYQ"  		 column="PKYQ" type="string"  maxlength="50"     description="排课要求"   />

</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/else/p_additive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="Additive" table="p_additive" description="添加剂配料数据统计" author="赵付录" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="string" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date |decimal选择其中一个
		description:描述,生成注释需要，页面内容
	 -->
	<property name="additiveNo"  column="additive_no"  type="string"  maxlength="50" description="添加剂批号"  /> 
	<property name="additiveType"  column="additive_type"  type="string"  maxlength="30" description="添加剂种类"/>
	<property name="formulaNo"  column="formula_no"  type="string"  maxlength="50" description="配方号"   />    
	<property name="weight"  column="weight"  type="decimal" description="重量/kg"   />         
	<property name="optTime"  column="opt_time"  type="date" description="时间" dateFmt="yyyy-MM-dd HH:mm:ss"  />             
	<property name="optor"  column="optor"  type="string"  maxlength="30" description="操作者"   />              
	<property name="bioFactory"  column="bio_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="bioNo"  column="bio_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="cooFactory"  column="coo_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="cooNo"  column="coo_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="mnoFactory"  column="mno_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="mnoNo"  column="mno_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="sboFactory"  column="sbo_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="sboNo"  column="sbo_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="nio2Factory"  column="nio2_factory"  type="string"  maxlength="80" description="厂家"   />  
	<property name="nio2No"  column="nio2_no"  type="string"  maxlength="50" description="检验单号"   />        
	<property name="nioFactory"  column="nio_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="nioNo"  column="nio_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="glassFactory"  column="glass_factory"  type="string"  maxlength="80" description="厂家"   />
	<property name="glassNo"  column="glass_no"  type="string"  maxlength="50" description="检验单号"   />      
	<property name="znoFactory"  column="zno_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="znoNo"  column="zno_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="croFactory"  column="cro_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="croNo"  column="cro_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="sioFactory"  column="sio_factory"  type="string"  maxlength="80" description="厂家"   />    
	<property name="sioNo"  column="sio_no"  type="string"  maxlength="50" description="检验单号"   />          
	<property name="temperature"  column="temperature"  type="decimal" description="温度/℃"    />
	<property name="humidness"  column="humidness"  type="decimal" description="湿度/%"       />
	<property name="inputTime"  column="input_time"  type="date" description="录入时间" dateFmt="yyyy-MM-dd HH:mm:ss"     />  
	
	
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/worker/kycg.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="kycg" table="kycg" description="科研成果表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="ID" column="ID" type="string" description="主键"/>
<property	name="CID"  		 column="CID" type="int"   description="成果类别编号"   />
<property	name="JSXM"  		 column="JSXM" type="string"  maxlength="10"     description="教师姓名"   />
<property	name="CGMC"      		 column="CGMC" type="string"  maxlength="50"   description="成果名称"     />
<property	name="JDDW"     		 column="JDDW" type="string"  maxlength="20"   description="鉴定单位"     />
<property	name="CGJDXX"      		 column="CGJDXX" type="string"  maxlength="20"   description="成果鉴定信息"      />
<property	name="FZ"  		 column="FZ" type="int"   description="分值"     />
<property	name="KYCGBZ"  		 column="KYCG_BZ" type="string"  maxlength="20"   description="备注"     />
<property	name="KECGRQ"  		 column="KECG_RQ" type="date"  maxlength="0"  description="科研成果鉴定日期" dateFmt="yyyy-MM-dd HH:mm:ss"     />
<property	name="KYCGXNXQ"  		 column="KYCG_XNXQ" type="string"  maxlength="50"     description="科研成果学年学期"   />
</entity>
