=== dingdinggithub/kevin-generator/src/main/resources/dtd/table.dtd
<!ELEMENT entity (id,property+)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT property (#PCDATA)>
	<!ATTLIST entity name CDATA #REQUIRED table CDATA #REQUIRED description CDATA #REQUIRED author CDATA #REQUIRED since CDATA #REQUIRED>
	<!ATTLIST id name CDATA #REQUIRED type ( int | long | string | date ) "string" description  CDATA #REQUIRED column CDATA #REQUIRED>
	<!ATTLIST property name CDATA #REQUIRED type ( int | long | string | date | decimal) "string" description  CDATA #REQUIRED column CDATA #REQUIRED maxlength CDATA #IMPLIED dateFmt CDATA #IMPLIED>

=== dingdinggithub/kevin-generator/target/classes/tables/else/inspectinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="InspectInfo" table="inspect_info" description="企业巡查信息" author="侯艳松" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="int" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date 选择其中一个
		description:描述,生成注释需要，页面内容
	 -->
	<property name="examinee" column="examinee" type="string" description="被检查人"/>
	<property name="legalPerson" column="legal_person" type="string" description="企业法人"/>
	<property name="businessAddress" column="business_address" type="string" description="经营地址"/>
	<property name="registerNo" column="register_no" type="date" description="注册号	"/>
	<property name="licenseNo" column="license_no" type="string" description="许可证号"/>
	<property name="businessScope" column="business_scope" type="string" description="经营范围"/>
	<property name="inspectAddress" column="inspect_address" type="string" description="巡检地址"/>
	<property name="inspectRecord" column="inspect_record" type="string" description="监督检查记录"/>
	<property name="inspectType" column="inspect_type" type="int" description="检查类别"/>
	<property name="inspector" column="inspector" type="string" description="巡检人员"/>
	<property name="fieldCondition" column="field_condition" type="string" description="现场情况"/>
	<property name="educationContent" column="education_content" type="string" description="法律宣传教育内容"/>
	<property name="handleSituation" column="handle_situation" type="string" description="处理情况"/>
	<property name="scenePhotos" column="scene_photos" type="string" description="现场照片"/>
	<property name="enterPrisename" column="enterprisename" type="string" description="企业名称"/>
	<property name="inspectInfo" column="inspect_info" type="string" description="企业巡查信息"/>
	<property name="escortUnit" column="escort_unit" type="string" description="单位陪同人员"/>
	<property name="mainProblem" column="main_problem" type="string" description="主要问题"/>
	<property name="equipmentType" column="equipment_type" type="string" description="特种设备类别"/>
	<property name="equipmentNumber" column="equipment_number" type="string" description="设备类别数量"/>
	<property name="mainInfo" column="main_info" type="string" description="检查主要内容"/>
	<property name="measures" column="measures" type="int" description="处理措施"/>
	<property name="inspectConclusion" column="inspect_conclusion" type="string" description="检查结论"/>
	<property name="checkPoints" column="check_points" type="string" description="药品经营企业检查项"/>
	<property name="remark" column="remark" type="string" description="备注"/>
	<property name="checkResult" column="check_result" type="int" description="检查结果"/>
	<property name="checkContents" column="check_contents" type="string" description="检查内容"/>
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/worker/csxx.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="csxx" table="csxx" description="参赛教师统计表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>
<property	name="JSGH"  		 column="JSGH" type="string"  maxlength="50" description="教师工号"   />
<property	name="XM"  		 column="XM" type="string"  maxlength="20"     description="姓名"   />
<property	name="CSKC"      		 column="CSKC" type="string"  maxlength="20"   description="参赛课程"     />
<property	name="SKSJ"     		 column="SKSJ" type="string"  maxlength="50"   description="上课时间"     />
<property	name="SKDD"      		 column="SKDD" type="string"  maxlength="20"   description="上课地点"      />
<property	name="PSZZ"  		 column="PSZZ" type="string"   maxlength="20" description="评审组长"     />
<property	name="CSXNXQ"  		 column="CSXNXQ" type="string"  maxlength="50"  description="参赛学年学期"    />
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/worker/sjkc.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="sjkc" table="sjkc" description="实践课程信息表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="ID" column="ID" type="string" description="主键"/>
<property	name="SJKCXNXQ"  		 column="SJKCXNXQ" type="string"  maxlength="20" description="实践课程学年学期"   />
<property	name="JSGH"  		 column="JSGH" type="string"  maxlength="20"     description="任课教师工号"   />
<property	name="SJKCDM"      		 column="SJKCDM" type="string"  maxlength="20"   description="实践课程代码"     />
<property	name="SJKCBZMC"     		 column="SJKCBZMC" type="string"  maxlength="20"   description="实践课程标准名称"     />
<property	name="SJKCKSQK"      		 column="SJKCKSQK" type="string"  maxlength="2"   description="实践课程开设情况"      />
<property	name="SKBJ"  		 column="SKBJ" type="string"   maxlength="20" description="授课班级"     />
<property	name="XMTM"  		 column="XMTM" type="string"  maxlength="20"  description="任课教师"    />
<property	name="RKJS"  		 column="RKJS" type="string"  maxlength="10"   description="项目题目"     />
<property	name="WPJSDW"  		 column="WPJSDW" type="string"  maxlength="20"     description="外聘教师单位"   />
<property	name="WPJSDH"      		 column="WPJSDH" type="string"  maxlength="20"   description="外聘教师电话"      />
<property	name="SKZS"  		 column="SKZS" type="string"   maxlength="10" description="授课周数"     />
<property	name="MZKS"  		 column="MZKS" type="string"  maxlength="10"   description="每周课时"     />
<property	name="SYSLX"  		 column="SYSLX" type="string"  maxlength="10"  description="实验室类型"    />
<property	name="ZKS"  		 column="ZKS" type="string"  maxlength="10"     description="总课时"   />
<property	name="SJKBZ"      		 column="SJKBZ" type="string"  maxlength="50"   description="实践课备注"      />
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/fupin/sctj_gd.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">                                  
<!--                                                                            
name:类名称,首字母大写                                                          
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)                             
description：（类的中文名称）页面中用到                                         
author：类的开发作者（注释会用到）                                              
version:类的开发版本                                                            
 -->                                                                            
<entity name="sctjGd" table="sctj_gd" description="生产条件_耕地表" author="孙强强" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>                  
	<!--                                                                          
		name:表示属性名称                                                           
		type：属性类型,int | long | string | date |decimal选择其中一个              
		description:描述,生成注释需要，页面内容                                     
	 -->
	<property name="JTBH" column="JTBH" type="string" maxlength="18" description="家庭编号" />
	<property name="GDCBGDMJ" column="GD_CBGDMJ" type="string" maxlength="50" description="耕地_承包耕地面积" /> 
	<property name="GDCBZZLB" column="GD_CBZZLB" type="string" maxlength="30" description="耕地_承包种植类别" /> 
	<property name="GDCBMCL" column="GD_CBMCL" type="decimal" maxlength="6" description="耕地_承包亩产量" /> 
	<property name="GDCBMTR" column="GD_CBMTR" type="decimal" maxlength="6" description="耕地_承包亩投入" /> 
	<property name="GDCDMCSY" column="GD_CDMCSY" type="decimal" maxlength="10" description="耕地_承包亩纯收益" /> 
	<property name="GDTGCGDMJ" column="GD_TGCGDMJ" type="decimal" maxlength="6" description="耕地_托管出耕地面积" /> 
	<property name="GDTGCZZLB" column="GD_TGCZZLB" type="string" maxlength="30" description="耕地_托管出种植类别" /> 
	<property name="GDTGZC" column="GD_TGZC" type="decimal" maxlength="6" description="耕地_托管支出" /> 
	<property name="GDTGCMCL" column="GD_TGCMCL" type="decimal" maxlength="6" description="耕地_托管出亩产量" /> 
	<property name="GDTGCMTR" column="GD_TGCMTR" type="decimal" maxlength="6" description="耕地_托管出亩投入" /> 
	<property name="GDTGCMSY" column="GD_TGCMSY" type="decimal" maxlength="6" description="耕地_托管出亩纯收益" /> 
	<property name="GDLZCGDMJ" column="GD_LZCGDMJ" type="decimal" maxlength="6" description="耕地_流转出耕地面积" /> 
	<property name="GDLZCZZLB" column="GD_LZCZZLB" type="string" maxlength="30" description="耕地_流转出种植类别" /> 
	<property name="GZLZSR" column="GZ_LZSR" type="decimal" maxlength="6" description="耕地_流转收入" /> 
	<property name="GDWGSR" column="GD_WGSR" type="decimal" maxlength="6" description="耕地_务工收入" /> 
	<property name="GDLZRGDMJ" column="GD_LZRGDMJ" type="decimal" maxlength="6" description="耕地_流转入耕地面积" /> 
	<property name="GDLZRZZLB" column="GD_LZRZZLB" type="string" maxlength="50" description="耕地_流转入种植类别" /> 
	<property name="GDLZRMCL" column="GD_LZRMCL" type="decimal" maxlength="6" description="耕地_流转入亩产量" /> 
	<property name="GDLZRMTR" column="GD_LZRMTR" type="decimal" maxlength="6" description="耕地_流转入亩投入" /> 
	<property name="GDLZRMCSY" column="GD_LZRMCSY" type="decimal" maxlength="6" description="耕地_流转入亩纯收益" /> 
	<property name="GDTGRGDMJ" column="GD_TGRGDMJ" type="decimal" maxlength="6" description="耕地_托管入耕地面积" /> 
	<property name="GDTGRZZLB" column="GD_TGRZZLB" type="string" maxlength="50" description="耕地_托管入种植类别" /> 
	<property name="GDTGRTGSR" column="GD_TGRTGSR" type="decimal" maxlength="6" description="耕地_托管入托管收入" /> 
	<property name="GDTGRMCL" column="GD_TGRMCL" type="decimal" maxlength="6" description="耕地_托管入亩产量" /> 
	<property name="GDTGRMYR" column="GD_TGRMYR" type="decimal" maxlength="6" description="耕地_托管入亩投入" /> 
	<property name="GDTGRMCSY" column="GD_TGRMCSY" type="decimal" maxlength="6" description="耕地_托管入亩纯收益" /> 
	<property name="inputTime" column="input_time" type="date" maxlength="0" description="录入时间" dateFmt="yyyy-MM-dd HH:mm:ss"/> 
	<property name="inputUser" column="input_user" type="string" maxlength="255" description="录入人" /> 
	
	</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/worker/kssjtj.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="kssjtj" table="kssjtj" description="考试数据统计表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="ID" column="ID" type="string" description="主键"/>
<property	name="NJ"  		 column="NJ" type="string"  maxlength="10"   description="年级"   />
<property	name="ZY"  		 column="ZY" type="string"  maxlength="20"     description="专业"   />
<property	name="KCDM"      		 column="KCDM" type="string"  maxlength="20"   description="课程代码"     />
<property	name="KCMC"     		 column="KCMC" type="string"  maxlength="10"   description="课程名称"     />
<property	name="KCXZ"      		 column="KCXZ" type="string"  maxlength="20"   description="课程性质"      />
<property	name="KSFS"  		 column="KSFS" type="string"  maxlength="10"   description="考试方式"     />
<property	name="CTJS"  		 column="CTJS" type="string"  maxlength="10"   description="出题教师"     />
<property	name="KSZC"  column="KSZC" type="int"     description="考试周次"   />
<property	name="PSCJBFB"  column="PSCJBFB" type="string"  maxlength="10"    description="平时成绩百分比" />
<property	name="ZKCJBFB"  column="ZKCJBFB" type="string"  maxlength="10"   description="中考成绩百分比"    />
<property	name="MKCJBFB"   	 column="MKCJBFB" type="string"  maxlength="10"   description="末考成绩百分比"     />
<property	name="SYCJBFB"  column="SYCJBFB" type="string"  maxlength="10"    description="实验成绩百分比" />
<property	name="BZ"  column="BZ" type="string"  maxlength="50"   description="备注"    />
<property	name="SJYW"   	 column="SJYW" type="string"  maxlength="10"   description="试卷有无"     />
<property	name="SFPK"   	 column="SFPK" type="string"  maxlength="10"   description="是否排考"     />
<property	name="KSTJXNXQ"      		 column="KSTJ_XNXQ" type="string"  maxlength="50"   description="考试统计学年学期"     />
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/else/p_burn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="Burn" table="p_burn" description="造粒料数据统计" author="赵付录" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="string" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date |decimal选择其中一个
		description:描述,生成注释需要，页面内容
	 -->                              
<property name="voltageGrade" column="voltage_grade" type="int" description="电压等级" />
<property name="chipNo" column="chip_no" type="string" maxlength="50" description="电阻片批号" />
<property name="specifNo" column="specif_no" type="string" maxlength="50" description="规格型号" />
<property name="inkilnNo" column="inkiln_no" type="int" description="待进窑数量/片" />
<property name="inkilnDate" column="inkiln_date" type="date" description="预烧_进窑时间_年/月/日" dateFmt="yyyy-MM-dd HH:mm:ss" />
<property name="inkilnOptor" column="inkiln_optor" type="string" maxlength="30" description="预烧_进窑时间_操作者" />
<property name="inkilnKilnNo" column="inkiln_kiln_no" type="int" description="预烧_进窑时间_窑炉编号" />
<property name="inkilnCupelTime" column="inkiln_cupel_time" type="date" description="预烧_首钵进窑时间" dateFmt="yyyy-MM-dd HH:mm:ss" />
<property name="cycleMin" column="cycle_min" type="int" description="预烧_进车周期/min" />
<property name="hotspaceTemp" column="hotspace_temp" type="decimal" description="预烧_高温区温度/℃" />
<property name="kilnStn" column="kiln_stn" type="int" description="预烧_窑炉有无异常（停电/上下温度不均匀/匣钵更换）" />
<property name="samplingPara" column="sampling_para" type="decimal" description="抽检参数(收缩率/%)" />
<property name="unqualNo" column="unqual_no" type="int" description="抽检参数(抽检合格数)" />
<property name="sliceDate" column="slice_date" type="date" description="抽检参数(出片日期)" dateFmt="yyyy-MM-dd HH:mm:ss" />
<property name="qualifiedNo" column="qualified_no" type="int" description="合格数" />
<property name="qualifiedPara" column="qualified_para" type="decimal" description="合格率" />
<property name="hierarchy" column="hierarchy" type="int" description="分层" />
<property name="incomplete" column="incomplete" type="int" description="缺豁" />
<property name="chromatism" column="chromatism" type="int" description="色差" />
<property name="breakage" column="breakage" type="int" description="断裂" />
<property name="swell" column="swell" type="int" description="鼓包" />
<property name="variant" column="variant" type="int" description="变形" />
<property name="other" column="other" type="int" description="其他" />
<property name="unqualReason" column="unqual_reason" type="string" maxlength="255" description="不合格情况说明" />
<property name="weatherTemp" column="weather_temp" type="decimal" description="预烧_天气情况_温度" />
<property name="weatherStn" column="weather_stn" type="string" maxlength="10" description="预烧_天气情况_天气" />
<property name="weatherWind" column="weather_wind" type="int" description="预烧_天气情况_风级" />
<property name="inputTime" column="input_time" type="date" description="录入时间，系统计入" dateFmt="yyyy-MM-dd HH:mm:ss" />

	
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/else/r_week .xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="WeekReport" table="r_week" description="质量周报" author="任春辉" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="string" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date |decimal选择其中一个
		description:描述,生成注释需要，页面内容
	 -->

<property name="reportName" column="report_name" type="string"  maxlength="80" description="报表名称"         /> 
<property name="startDate" column="start_date" type="date"  description="起始日期" dateFmt="yyyy-MM-dd"/>
<property name="endDate" column="end_date" type="date"  description="截至日期"  dateFmt="yyyy-MM-dd"/>
<property name="submitDepart" column="submit_depart" type="string"  maxlength="50" description="报送部门"         />
<property name="submitOperator" column="submit_operator" type="string"  maxlength="50" description="提交人"         />
<property name="examineOperator" column="examine_operator" type="string"  maxlength="50" description="审核人"         />
<property name="submitCycle" column="submit_cycle" type="string"  maxlength="50" description="提报周期"         />
<property name="overview" column="overview" type="string"  maxlength="255" description="综述"         />
<property name="thisweekDesc" column="thisweek_desc" type="string"  maxlength="255" description="本周情况描述"         />
<property name="qualitySituation" column="quality_situation" type="string"  maxlength="255" description="腿釉试验回收料压制片质量情况"         />
<property name="processFeedback" column="process_feedback" type="string"  maxlength="255" description="过程反馈不合格处理及验证"         />
<property name="headerDate" column="header_date" type="date"  maxlength="0" description="表头日期"  dateFmt="yyyy-MM-dd"       />
<property name="headerWeek" column="header_week" type="int"  maxlength="0" description="表头周"         />
<property name="inputTime" column="input_time" type="date"  description="登记时间"    dateFmt="yyyy-MM-dd"     />
<property name="inputUser" column="input_user" type="string"  maxlength="50" description="操作人"         />
                                                                                                                                                                                                                                      
</entity>

=== dingdinggithub/kevin-generator/target/classes/tables/worker/jszlkphz.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="jszlkphz" table="jszlkphz" description="教学质量考评汇总表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>
<property	name="JSGH"  		 column="JSGH" type="string"  maxlength="20" description="教师工号"   />
<property	name="JSXM"  		 column="JSXM" type="string"  maxlength="20"     description="教师姓名"   />
<property	name="XSPJDF"      		 column="XSPJDF" type="string"  maxlength="10"   description="学生评教得分"     />
<property	name="THPJDF"     		 column="THPJDF" type="string"  maxlength="10"   description="同行评价得分"     />
<property	name="YSJSGGDF"      column="YSJSGGDF" type="string"  maxlength="50"   description="教学改革与研究得分(原始分)"      />
<property	name="JSGGDF"  		 column="JSGGDF" type="string"   maxlength="10" description="教学改革与研究得分"     />
<property	name="YSTSJSNLDF"  		 column="YSTSJSNLDF" type="string"  maxlength="10"   description="提升教学能力得分(原始分)"     />
<property	name="TSJSNLDF"  		 column="TSJSNLDF" type="string"  maxlength="10"  description="提升教学能力得分"    />
<property	name="ZLPJZF"  		 column="ZLPJZF" type="string"  maxlength="10"     description="质量评价总分"   />
<property	name="ZLPJDJ"      		 column="ZLPJDJ" type="string"  maxlength="50"   description="质量评价等级"      />
<property	name="KPXNXN"  		 column="KPXNXN" type="string"   maxlength="50" description="考评学年学期"     />
</entity>
