=== dingdinggithub/kevin-generator/src/main/resources/dtd/table.dtd
<!ELEMENT entity (id,property+)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT property (#PCDATA)>
	<!ATTLIST entity name CDATA #REQUIRED table CDATA #REQUIRED description CDATA #REQUIRED author CDATA #REQUIRED since CDATA #REQUIRED>
	<!ATTLIST id name CDATA #REQUIRED type ( int | long | string | date ) "string" description  CDATA #REQUIRED column CDATA #REQUIRED>
	<!ATTLIST property name CDATA #REQUIRED type ( int | long | string | date | decimal) "string" description  CDATA #REQUIRED column CDATA #REQUIRED maxlength CDATA #IMPLIED dateFmt CDATA #IMPLIED>

=== dingdinggithub/kevin-generator/src/main/resources/tables/mem/user.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="user" table="t_mem_user" description="用户" author="丁海峰" since="1.0">
	<!--
	    主键
	 -->
	<id name="id" column="id" type="long" description="主键"/>

	<property	name="username"   column="username" type="string"  maxlength="50"   description="用户名"  />
	<property	name="password"   column="password" type="string"  maxlength="40"   description="用户密码"  />
	<property	name="status"   column="status" type="int"  maxlength="4"   description="用户状态"  />
	<property	name="telephone"   column="telephone" type="string"  maxlength="13"   description="手机号"  />
	<property	name="mail"   column="mail" type="string"  maxlength="20"   description="邮箱"  />
	<property	name="deptId"   column="dept_id" type="long"  maxlength="4"   description="部门id"  />

	<!--<property	name="remark"   column="remark" type="string"  maxlength="200"   description="备注"  />
	<property	name="isDeleted"   column="is_deleted" type="int"  maxlength="4"   description="是否已删除" />
	<property	name="createBy"   column="create_by" type="string"  maxlength="40"   description="创建人"  />
	<property	name="updateBy"   column="update_by" type="string"  maxlength="40"   description="更新人"  />
	<property	name="createTime"   column="create_time" type="date" description="创建时间"  />
	<property	name="updateTime"   column="update_time" type="date" description="更新时间"  />-->



</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/worker/jsxx.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">                                                                                                              
<entity name="jsxx" table="jsxx" description="教师信息表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="JSGH"  column="JSGH"  type="string"  description="主键"/> 
	<property name="JSDLMM"  column="JSDLMM"  type="string"  maxlength="20"  description="教师登陆密码" />                 
  <property name="DW"  column="DW"  type="string"  maxlength="10"  description="单位" />
  <property name="JSXM"  column="JSXM"  type="string"  maxlength="10"  description="教师姓名" />
  <property name="XB"  column="XB"  type="string"  maxlength="2"  description="性别" />
  <property name="CSRQ"  column="CSRQ"  type="date"  maxlength="0"  description="出生日期" dateFmt="yyyy-MM-dd HH:mm:ss" />
  <property name="ZZMM"  column="ZZMM"  type="string"  maxlength="10"  description="政治面貌" />
  <property name="MZ"  column="MZ"  type="string"  maxlength="10"  description="民族" />
  <property name="SFZH"  column="SFZH"  type="string"  maxlength="20"  description="身份证号" />
  <property name="ZW"  column="ZW"  type="string"  maxlength="10"  description="职务" />
  <property name="XGW"  column="XGW"  type="string"  maxlength="10"  description="现岗位" />
  <property name="SFJYJSZG"  column="SFJYJSZG"  type="string"  maxlength="2"  description="是否具有教师资格" />
  <property name="ZCPDSJ"  column="ZCPDSJ"  type="string"  maxlength="10"  description="职称评定时间" />
  <property name="DYXL"  column="DYXL"  type="string"  maxlength="10"  description="第一学历" />
  <property name="DYXLBYYX"  column="DYXL_BYYX"  type="string"  maxlength="20"  description="第一学历毕业院校" />
  <property name="DYXLZY"  column="DYXL_ZY"  type="string"  maxlength="30"  description="第一学历专业" />
  <property name="DYXLBYSJ"  column="DYXL_BYSJ"  type="string"  maxlength="20"  description="第一学历毕业时间" />
  <property name="ZGXLBYYX"  column="ZGXL_BYYX"  type="string"  maxlength="20"  description="最高学历毕业院校" />
  <property name="ZGXL"  column="ZGXL"  type="string"  maxlength="10"  description="最高学历" />
  <property name="ZGXLZY"  column="ZGXL_ZY"  type="string"  maxlength="20"  description="最高学历专业" />
  <property name="ZGXLBYSJ"  column="ZGXL_BYSJ"  type="string"  maxlength="20"  description="最高学历毕业时间" />
  <property name="SJH"  column="SJH"  type="string"  maxlength="20"  description="手机号" />
  <property name="EMAIL"  column="EMAIL"  type="string"  maxlength="20"  description="教室email" />
  <property name="BGDH"  column="BGDH"  type="string"  maxlength="20"  description="办公电话" />
  </entity>

=== dingdinggithub/kevin-generator/target/classes/tables/fupin/Xqtpljgh.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="xqtpljgh" table="xqtpljgh" description="县区脱贫路径规划 " author="niuxin" since="1.0">
<id name="QHDM" column="QHDM" type="string" description="区划代码"/>   
	<property name="TBND" column="TBND" type="string" maxlength="4" description="填报年度"/> 
	<property name="QHMC" column="QHMC" type="string" maxlength="20" description="县区名称" />
 	<property name="JHND" column="JHND" type="string" maxlength="4" description="计划年度" />
 	<property name="FZSCZZHS"    column="FZSC_ZZHS"      type="int"    description="发展生产_种植户数"/>
 	<property name="FZSCZZRKS"   column="FZSC_ZZRKS"      type="int"    description="发展生产_种植人口数"   />
 	<property name="FZSCYZHS"    column="FZSC_YZHS"      type="int"    description="发展生产_养殖户数"   />
 	<property name="FZSCYZRKS"   column="FZSC_YZRKS"      type="int"    description="发展生产_养殖人口数"   />
 	<property name="FZSCJGHS"   column="FZSC_JGHS"      type="int"    description="发展生产_加工户数"   />
 	<property name="FZSCJGRKS"   column="FZSC_JGRKS"      type="int"    description="发展生产_加工人口数"   />
 	<property name="FZSCSFHS"    column="FZSC_SFHS"      type="int"    description="发展生产_商服户数"   />
 	<property name="FZSCSFRKS"   column="FZSC_SFRKS"      type="int"    description="发展生产_商服人口数"   />
 	<property name="FZSCQTHS"    column="FZSC_QTHS"      type="int"    description="发展生产_其他户数"   />
 	<property name="FZSCQTRKS"   column="FZSC_QTRKS"      type="int"    description="发展生产_其他人口数"   />
 	<property name="YDBQHS"      column="YDBQ_HS"      type="int"    description="易地搬迁_户数"   />
 	<property name="YDBQRKS"     column="YDBQ_RKS"      type="int"    description="易地搬迁_人口数"   />
 	<property name="FZJYHS"     column="FZJY_HS"      type="int"    description="发展教育_户数"   />
 	<property name="FZJYRKS"     column="FZJY_RKS"      type="int"    description="发展教育_人口数"   />
 	<property name="STBCHS"      column="STBC_HS"      type="int"    description="生态补偿_户数"   />
 	<property name="STBCRKS"     column="STBC_RKS"      type="int"    description="生态补偿_人口数"   />
 	<property name="SBDDHS"     column="SBDD_HS"      type="int"    description="社会兜底_户数"   />
 	<property name="SBDDRKS"     column="SBDD_RKS"      type="int"    description="社会兜底_人口数"   />
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/else/Permission.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "../dtd/table.dtd">
<!--
name:类名称,首字母大写
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)
description：（类的中文名称）页面中用到
author：类的开发作者（注释会用到）
version:类的开发版本
 -->
<entity name="Permissions" table="sys_permissions" description="权限" author="余进" since="1.0">
	<!-- 
		主键
	 -->
	<id name="id" column="id" type="string" description="主键"/>
	<!-- 
		name:表示属性名称
		type：属性类型,int | long | string | date 选择其中一个
		description:描述,生成注释需要，页面内容
	 -->
	<property name="name" column="name" type="string" description="权限名称"/>
	<property name="code" column="code" type="string" description="权限码"/>
	<property name="pcode" column="pcode" type="string" description="树形码"/>
	<property name="url" column="url" type="string" description="URL"/>
	<property name="status" column="status" type="int" description="权限状态"/>
	<property name="type" column="type" type="int" description="权限类型"/>
</entity>

=== dingdinggithub/kevin-generator/target/classes/tables/worker/jspx.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="jspx" table="jspx" description="教师培训信息表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>
<property	name="PXNR"  		 column="PXNR" type="string"  maxlength="50" description="培训内容"   />
<property	name="ZZPXDW"  		 column="ZZPXDW" type="string"  maxlength="20"     description="组织培训单位"   />
<property	name="PXJB"      		 column="PXJB" type="string"  maxlength="10"   description="培训级别"     />
<property	name="PXSJ"  		 column="PXSJ" type="date"  maxlength="0"  description="培训时间" dateFmt="yyyy-MM-dd"    />
<property	name="PXDD"     		 column="PXDD" type="string"  maxlength="20"   description="培训地点"     />
<property	name="PXRY"      		 column="PXRY" type="string"  maxlength="100"   description="参加培训人员"      />
<property	name="PXRS"  		 column="PXRS" type="int"  description="参加培训人数"    />
<property	name="PXJF"      		 column="PXJF" type="string"  maxlength="10"   description="培训经费"      />
<property	name="PXJG"      		 column="PXJG" type="string"  maxlength="50"   description="培训经结果"      />
<property	name="PXXNXQ"  		 column="PXXNXQ" type="string"  maxlength="50"  description="培训学年学期"    />
</entity>

=== dingdinggithub/kevin-generator/target/classes/tables/worker/jtryxx.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="jtryxx" table="jtryxx" description="学院集体荣誉信息表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>
<property	name="BZMC"  		 column="BZMC" type="string"  maxlength="50" description="表彰名称"   />
<property	name="HJBM"  		 column="HJBM" type="string"  maxlength="20"     description="获奖部门"   />
<property	name="BJBM"      		 column="BJBM" type="string"  maxlength="20"   description="颁奖部门"     />
<property	name="HJJB"     		 column="HJJB" type="string"  maxlength="20"   description="获奖级别"     />
<property	name="HJRQ"      		 column="HJRQ" type="date"  maxlength="0"  description="获奖日期" dateFmt="yyyy-MM-dd"      />
<property	name="HJXNXQ"  		 column="HJXNXQ" type="string"  maxlength="50"  description="荣誉获得学年学期"    />
</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/fupin/shtj.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">                                     
<!--                                                                            
name:类名称,首字母大写                                                          
package:包名,方面后面的扩展(eg：com.zs.xybb.domian)                             
description：（类的中文名称）页面中用到                                         
author：类的开发作者（注释会用到）                                              
version:类的开发版本                                                            
 -->                                                                            
<entity name="shtj" table="shtj" description="生活条件表" author="孙强强" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="id" column="id" type="string" description="主键"/>                  
	<!--                                                                          
		name:表示属性名称                                                           
		type：属性类型,int | long | string | date |decimal选择其中一个              
		description:描述,生成注释需要，页面内容                                     
	 -->
	<property name="JTBH" column="JTBH" type="string" maxlength="18" description="家庭编号" />
	<property name="ZFZFJG" column="ZF_ZFJG" type="string" maxlength="50" description="住房_住房结构" /> 
	<property name="ZFZFMJ" column="ZF_ZFMJ" type="decimal" maxlength="8" description="住房_住房面积" /> 
	<property name="ZFSFWF" column="ZF_SFWF" type="string" maxlength="5" description="住房_是否危房" /> 
	<property name="ZFCSLB" column="ZF_CSLB" type="string" maxlength="20" description="住房_厕所类别" /> 
	<property name="ZFSFTSFYD" column="ZF_SFTSFYD" type="string" maxlength="2" description="住房_通生活用电" /> 
	<property name="ZFSFTSCYD" column="ZF_SFTSCYD" type="string" maxlength="2" description="住房_通生产用电" /> 
	<property name="YSYSKL" column="YS_YSKL" type="string" maxlength="2" description="饮水_饮水困难" /> 
	<property name="YSYSAQ" column="YS_YSAQ" type="string" maxlength="2" description="饮水_饮水安全" /> 
	<property name="YSYSLY" column="YS_YSLY" type="string" maxlength="30" description="饮水_饮水来源" /> 
	<property name="ZYALLX" column="ZYALLX" type="string" maxlength="20" description="主要燃料类型" /> 
	<property name="RHLLX" column="RHLLX" type="string" maxlength="20" description="入户路类型" /> 
	<property name="YYHLZL" column="YYHLZL" type="decimal" maxlength="8" description="与硬化路距离" /> 
	<property name="SFGMCL" column="SFGMCL" type="string" maxlength="2" description="是否购买车辆" /> 
	<property name="CLLX" column="CLLX" type="string" maxlength="30" description="车辆类型" /> 
	<property name="SFFGTX" column="SFFGTX" type="string" maxlength="2" description="是否覆盖通信" /> 
	<property name="SFFGHLW" column="SFFGHLW" type="string" maxlength="2" description="是否覆盖互联网" /> 
	<property name="SFJRHZS" column="SFJRHZS" type="string" maxlength="2" description="是否加入合作社" /> 
	<property name="SFJRLTQY" column="SFJRLTQY" type="string" maxlength="2" description="是否加入龙头企业" /> 
	<property name="SFJRJTNC" column="SFJRJTNC" type="string" maxlength="2" description="是否加入家庭农场" /> 
	<property name="JTFZQK" column="JTFZQK" type="decimal" maxlength="8" description="家庭负债情况" /> 
	<property name="inputTime" column="input_time" type="date" maxlength="0" description="录入时间" dateFmt="yyyy-MM-dd HH:mm:ss"/> 
	<property name="inputUser" column="input_user" type="string" maxlength="255" description="录入人" /> 

	
	
	
	
	</entity>

=== dingdinggithub/kevin-generator/src/main/resources/tables/worker/kcsj.xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<!DOCTYPE entity SYSTEM "../../dtd/table.dtd">
<entity name="kcsj" table="kcsj" description="实践课程信息表" author="牛鑫" since="1.0">
	<!--                                                                          
		主键                                                                        
	 -->                                                                          
	<id name="ID" column="ID" type="string" description="主键"/>
<property	name="KCSJXNXQ"  		 column="KCSJXNXQ" type="string"  maxlength="20" description="课程设计学年学期"   />
<property	name="JSGH"  		 column="JSGH" type="string"  maxlength="20"     description="任课教师工号"   />
<property	name="KCSJMC"      		 column="KCSJMC" type="string"  maxlength="20"   description="课程设计名称"     />
<property	name="KCSJBJ"     		 column="KCSJBJ" type="string"  maxlength="20"   description="课程设计班级"     />
<property	name="ZDJS"      		 column="ZDJS" type="string"  maxlength="20"   description="指导教师"      />
<property	name="XMMC"  		 column="XMMC" type="string"   maxlength="20" description="项目名称"     />
<property	name="ZHXSJXM"  		 column="ZHXSJXM" type="string"  maxlength="2"  description="是否是综合性、设计性项目"    />
<property	name="ZC"  		 column="ZC" type="string"  maxlength="10"   description="周次"     />
<property	name="XQ"  		 column="XQ" type="string"  maxlength="10"     description="星期"   />
<property	name="JC"      		 column="JC" type="string"  maxlength="10"   description="节次"      />
<property	name="SKRS"  		 column="SKRS" type="string"   maxlength="10" description="授课人数"     />
<property	name="ZB"  		 column="ZB" type="string"  maxlength="10"   description="组别"     />
<property	name="SYS"  		 column="SYS" type="string"  maxlength="10"  description="实验室"    />
</entity>
